Fix RPM signing, now integrated to RPM build process

diff --git a/.github/workflows/generic_semodule_build.yml b/.github/workflows/generic_semodule_build.yml
--- a/.github/workflows/generic_semodule_build.yml
+++ b/.github/workflows/generic_semodule_build.yml
@@ -21,7 +21,6 @@ on:
       build_os_matrix:
         description: 'Provides the relative path of the SELinux files'
         required: false
-        #default: '[ "centos_7", "almalinux8", "centos_stream9", "fedora_36", "fedora_37", "fedora_38", "fedora_39", "fedora_40" ]'
         default: '[ "almalinux8", "centos_stream9", "fedora_37", "fedora_38", "fedora_39", "fedora_40" ]'
         type: string
       release_upload_url:
@@ -57,8 +56,8 @@ jobs:
     env:
       gpg_private_key_file: private_key.gpg
       gpg_private_key: ${{ secrets.gpg_private_key }}
+      gpg_private_key_password: ${{ secrets.gpg_private_key_password }}
       rpms_dir: rpmbuild/RPMS/
-      signed_rpms_dir: signed-RPMS/
 
     steps:
       - name: Checkout code
@@ -74,6 +73,11 @@ jobs:
           ref: ${{ matrix.os }}
           path: ACTIONS-build
 
+      - name: Create private key file from secret.
+        run: |
+          echo "${gpg_private_key}" | base64 -di > ${gpg_private_key_file}
+          echo "${gpg_private_key_password}" > .${gpg_private_key_file}.passphrase
+
       - name: Call Docker RPM build
         id: dockerbuild
         uses: ./ACTIONS-build
@@ -83,41 +87,29 @@ jobs:
           selinux_files_location: ${{ inputs.selinux_files_location }}
           provided_version: ${{ inputs.provided_version }}
           provided_release: ${{ inputs.provided_release }}
-
-      - name: Create private key file from secret.
-        run: |
-          echo "${gpg_private_key}" | base64 -di > ${gpg_private_key_file}
-          [ -d ${signed_rpms_dir} ] || mkdir -p ${signed_rpms_dir}
-      
-      - name: Call Docker RPM sign
-        uses: lhqg/rpmsign@master
-        with:
-          gpg_private_key: ${{ env.gpg_private_key_file }}
-          gpg_private_key_password: ${{ secrets.gpg_private_key_password }}
           gpg_name: ${{ vars.RPM_SIGNING_KEY_NAME }}
-          rpm_folder: ${{ env.rpms_dir }}
-          output_folder: ${{ env.signed_rpms_dir }}
-          
+          gpg_private_key_file: ${{ env.gpg_private_key_file }}
+
       - name: Upload RPMs
         id: upload_rpms
         run: |
 
-          if [ -n "${signed_rpms_dir}" -a -d "${signed_rpms_dir}" ]
+          if [ -n "${rpms_dir}" -a -d "${rpms_dir}" ]
           then
             UPLOAD_URL=$( sed -e 's/{?name,label}/?name/' <<< '${{ inputs.release_upload_url }}' )
-            echo "Uploading to ${UPLOAD_URL}"
+            echo "::notice title={title}::Uploading to ${UPLOAD_URL}"
 
-            ls -la ${signed_rpms_dir}
+            ls -lR ${rpms_dir}
 
             rc=0
             count=0
 
-            for rpm in $( find ${signed_rpms_dir} -type f -name '*.rpm' )
+            for rpm in $( find ${rpms_dir} -type f -name '*.rpm' )
             do 
               RPM_FILE_NAME=$(basename ${rpm})
 
               # Upload RPM
-              echo "-- Uploading ${RPM_FILE_NAME}:"
+              echo "::debug title={debug}::Uploading ${RPM_FILE_NAME}:"
               curl \
                 -X POST \
                 -H "Accept: application/vnd.github+json" \
@@ -125,13 +117,14 @@ jobs:
                 -H "Content-Type: application/octet-stream" \
                 -T ${rpm} \
                 ${UPLOAD_URL}=${RPM_FILE_NAME}
-              rc=$(( $rc + $? ))
-              [ $rc -eq 0 ] && count=$( $count + 1 )
+              rc_curl=$?
+              echo "::debug title={debug}::Upload return code: ${rc_curl}"
+              [ $rc_curl -eq 0 ] && count=$(( $count + 1 )) || rc=1
             done
-            echo "Total RPMs uploaded: ${count}."
+            echo "::notice title={title}::Total RPMs uploaded: ${count}."
             [ $count -lt 1 ] && rc=1
           else
-            echo "Fatal: the signed RPMs directory is not set or does not exist."
+            echo "::error title={title}:: Fatal: the signed RPMs directory is not set or does not exist."
             rc=1
           fi
           exit $rc
